### ISSUE TITLE
Raspberry Pi grafana issue

### ISSUE THREAD

**Issue by PlinyElderATX** [frdmn/docker-speedtest#2]
Trying to get this running on a raspberry pi fails due to what I suspect to be the wrong grafana version:
`grafana      | standard_init_linux.go:211: exec user process caused "exec format error"
grafana exited with code 1` 

I'm a bit new to this and am working on solving it but not getting terribly far.

**Comment by frdmn** [comment]
Raspberry Pi uses ARM based architecture but the images used in our `docker-compose.yml` has only amd64 support: https://hub.docker.com/layers/grafana/grafana/5.1.0/images/sha256-ed6c9eb28b018bf01644dde28e05357fe2f11138ca232319015a6bac259fc873?context=explore

Try to use the version 5.4.4 - it seems that this image was built for arm64: https://hub.docker.com/r/grafana/grafana/tags?page=1&name=5.4.4

**Comment by frdmn** [comment]
Let me know if you still have issues with this
